language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
# Python 3.7 and 3.8 are not available as standard in travis CI
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8-dev
          dist: bionic
          sudo: true

install:
    - pip3 install pyflakes
    - pip3 install -r requirements.txt

script:
    - python3 -m unittest
    - find . -name '*.py' -print0 | xargs -0 pyflakes
    - pip3 install .
    - pwmanager -h
